/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package machine.view;

/**
 *
 * @author Ryan Ball
 */
public class ActivationRecord extends javax.swing.JPanel {

    private final int returnAddress;
    private final int dynamicLink;
//    private final String call = "Main";
    
    /**
     * Creates new form StackRecordPanel
     */
    public ActivationRecord() {
        initComponents();
        
        callTextButton.setText("Main");
        this.dynamicLink = 2;
        this.returnAddress = 1;
        String rA = "0x" + Integer.toHexString(returnAddress).toUpperCase();
        String dL = "0x" + Integer.toHexString(dynamicLink).toUpperCase();
        returnField.setText("Return Address: " + rA 
                        + "\nDynamic Link: " + dL);
    }
    
    /**
     * Constructor
     * @param returnAddress
     * @param dynamicLink
     * @param call
     */
    public ActivationRecord(String call, int returnAddress, int dynamicLink) {
            initComponents();
            callTextButton.setText(call);
            this.dynamicLink = dynamicLink;
            this.returnAddress = returnAddress;
            String rA = "0x" + Integer.toHexString(returnAddress).toUpperCase();
            String dL = "0x" + Integer.toHexString(dynamicLink).toUpperCase();
            returnField.setText("Return Address: " + rA 
                            + "\nDynamic Link: " + dL);
    }

    /**
     * 
     * @return integer return address
     */
    public int getReturnAddress() {
            return returnAddress;
    }

    /**
     * 
     * @return integer dynamic link - old base pointer
     */
    public int getDynamicLink() {
            return dynamicLink;
    }
    
    public void setTextAreaVisible(boolean value) {
        returnField.setVisible(value);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        callTextButton = new javax.swing.JButton();
        returnField = new javax.swing.JTextArea();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        callTextButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        callTextButton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        callTextButton.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        callTextButton.setPreferredSize(new java.awt.Dimension(190, 40));
        callTextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                callTextButtonActionPerformed(evt);
            }
        });

        returnField.setEditable(false);
        returnField.setColumns(20);
        returnField.setRows(5);
        returnField.setPreferredSize(new java.awt.Dimension(190, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(returnField, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(callTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(callTextButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(returnField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void callTextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_callTextButtonActionPerformed
        if (returnField.isVisible()) {
            returnField.setVisible(false);
        }
        else {
            returnField.setVisible(true);
        }
    }//GEN-LAST:event_callTextButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton callTextButton;
    private javax.swing.JTextArea returnField;
    // End of variables declaration//GEN-END:variables
}
